### ISSUE TITLE
Async Support?

### ISSUE THREAD

**Issue by defc0n** [markwellis/net-amqp-rabbitmq#39]
Is there any interest in providing asynchronous support?  I noticed there is an AnyEvent::RabbitMQ already that I believe uses Net::AMQP instead.

**Comment by manchicken** [comment]
If you wanted to contribute a wrapper for that, that'd be cool with me. At the moment I think we're working on building out a more robust implementation of the librabbitmq-c library.

**Comment by pmorch** [comment]
I see that this issue is closed, but I was also wondering about async support.

@manchicken, you suggest a wrapper. But is that even possible? How would AnyEvent know / be woken up when there are messages ready for `$mq->recv()`. Won't it need to get hold of a socket to `select()` on?

Given the published API, I suspect the only possibility is for busy-waiting and that'll give horrible performance. Did I miss something?

**Comment by zbentley** [comment]
You can probably get the sockfd number out using the published API, but generally I think that this library is meant to be used synchronously. Out of curiosity, what did you find to be lacking in AnyEvent::RabbitMQ?

**Comment by pmorch** [comment]
At this time, 02:32AM, I'm a little confused about all the RabbitMQ interfaces available for Perl:
* Net::RabbitMQ we abandoned because of it included an obsolete rabbitmq-c. This is fixed by Net::AMQP::RabbitMQ.
* We also abandoned Net::AMQP-based options, Net::RabbitFoot and AnyEvent::RabbitMQ back in 2013, but I don't remember why. And I've lost the documentation as to why... (Performance?)
* We're currently using Net::STOMP, but the RabbitMQ STOMP interface provides fewer features and Net::AMQP::RabbitMQ is 4 times faster.
* Are there even more contenders?

**Comment by manchicken** [comment]
I don't understand what your async goal is, so I'm not sure how to answer
your question.

What are you trying to do?

**Comment by pmorch** [comment]
Ok, so now I've confused everybody! :-)

First, for "Why Net::AMQP::RabbitMQ?" - Some performance test numbers, for publishing and receiving 100,000 "Hi there!" messages:

* Net::RabbitFoot: 33.8 sec
* Net::STOMP: 16.6 sec
* Net::AMQP::RabbitMQ: 4.6 sec

This is why I want to use  Net::AMQP::RabbitMQ. It is fast. If there is interest, I'll clean up my test code and post a gist.

About async: In my event-loop based process, I want to react to both incoming requests on a socket and `$mq->recv()` which could occur in any order. That is what something like AnyEvent is for.  I'm not sure I understand what is unclear about async.

I want to have an "event loop" that issues callbacks if any one of N things occur, of which `$mq->recv()` is only one possibility, so blocking in a `$mq->recv()` call is not an option. The only other possibility is  testing it e.g. every X ms, but that'll give horrible CPU load and/or throughput.

That is why (i think) we need access to the file descriptor so that one can `select()` on that and any other sockets (e.g. the one for the incoming requests), so that we can be notified when there is actual data to be received on `$mq`'s socket or on any other socket.

Most (not all) of our use cases for RabbitMQ are synchronous, but I'd like a single high-performant solution, and I think Net::AMQP::RabbitMQ is it! Especially if we could integrate with e.g. AnyEvent.

I hope this is clearer.

**Comment by zbentley** [comment]
I understand your use case and it makes sense. However, I doubt that this module will ever efficiently integrate with an event loop, simply because the underlying `librabbitmq` driver is fairly opinionatedly synchronous, at least so far (see [https://github.com/alanxz/rabbitmq-c/issues/84](https://github.com/alanxz/rabbitmq-c/issues/84) for more info).

Where performance is a concern, I'd suggest looking into two things with regard to AnyEvent-based evented RabbitMQ drivers (AnyEvent::RabbitMQ or RabbitFoot--I got the impression that AnyEvent::RabbitMQ is better supported and tends to be faster, and you can make certain operations on it synchronous a la RabbitFoot by using `condvar` objects):

- Changing your AnyEvent backend. It's possible your slowness is in the event loop itself.
- Relying more heavily on the advantages of evented programming: your individual send/serialize/recv socket operations don't *need* to be fast if they get "multiplexed" by the event loop wit the other stuff your process needs to be doing. I understand that this is not an option for some use cases, though.

**Comment by pmorch** [comment]
Thanks, @zbentley for your answer. In reading https://github.com/alanxz/rabbitmq-c/issues/84, the first comment after the OP points to https://github.com/alanxz/rabbitmq-c/issues/77#issuecomment-10340723, where it says:

> Your analysis is correct. Currently the library doesn't directly support interrupting calls into the library.
>
> That said the library does support extracting the socket fd from the connection object. So it is possible with a bit if work to use the select system call with a timeout parameter of your choosing to make the library behave in a non blocking manner.
>
> The SimpleAmqpClient library which wraps rabbitmq-c does this as an example when consuming messages.

Pretty much what I've been saying above, isn't it?

I currently believe that if Net::AMQP::RabbitMQ's Perl API would allow me to extract the socket fd of the underlying socket, I could use that to create an AnyEvent wrapper. Whenever the socket is readable, I'd try `$mq->recv(-1)` to see if there was a new message.

But I would need access to the socket file descriptor number.

I suspect that adding access to the socket fd in the XS code wouldn't be that difficult. Would this project be open to such a pull-request?

**Comment by pmorch** [comment]
In fact, `$mq->get_sockfd()` already does exaclty what one would need. So all that would be needed would be a a pull request for the perldoc to make this part of the documented API... ;-)

**Comment by markwellis** [comment]
It's purposely not part of the documented api because of this warning

https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/blob/master/RabbitMQ.xs#L1809

But it's there so you can use it if you really want to.

I've done async stuff using IO::Async, via forking. Not sure if that's any
use to you though

**Comment by pmorch** [comment]
Ok, I think Async has been beaten to death now. I'll leave it. Thanks for your inputs, guys!
